### ISSUE TITLE
Unusable {-# UNPACK #-} pragmas.

### ISSUE THREAD

**Issue by chowells79** [ollef/Earley#1]
[2 of 4] Compiling Text.Earley.Parser ( Text/Earley/Parser.hs, dist/build/Text/Earley/Parser.o )

    Text/Earley/Parser.hs:83:3: Warning:
        Ignoring unusable UNPACK pragma on the third argument of ‘State’
        In the definition of data constructor ‘State’
        In the data declaration for ‘State’

    Text/Earley/Parser.hs:92:3: Warning:
        Ignoring unusable UNPACK pragma on the second argument of ‘Cont’
        In the definition of data constructor ‘Cont’
        In the data declaration for ‘Cont’

    Text/Earley/Parser.hs:92:3: Warning:
        Ignoring unusable UNPACK pragma on the fourth argument of ‘Cont’
        In the definition of data constructor ‘Cont’
        In the data declaration for ‘Cont’

In all cases, those arguments are `Arg` values, and `Arg` is a type alias for a function type.  Function types can't be unpacked, since they aren't thin wrappers around primitives.

**Comment by ollef** [comment]
Thanks for your report.

You're right. In fact, I just realised that the cabal file gives the -funbox-strict-fields flag so all UNPACKs could probably be removed. Out of interest, what version of GHC are you using? I'm not getting those warnings even with -Wall running 7.10.1.

**Comment by ollef** [comment]
Fixed by 6fc5388db9365267618321b52f17792c6f30423c.

**Comment by chowells79** [comment]
GHC 7.10.1, just building with cabal.  Not sure why I got the warnings and you didn't.
