### ISSUE TITLE
rebuild the documentation with --hyperlinked-source

### ISSUE THREAD

**Issue by sboosali** [ollef/Earley#13]
the feature is only available in haddock's master branch. for example, you can run: 

    cabal haddock --with-haddock="$HOME/haddock/.cabal-sandbox/bin/haddock" --haddock-options="--hyperlinked-source"

after building haddock from source, in a sandbox (https://github.com/haskell/haddock): 

    git clone https://github.com/haskell/haddock.git
    cd haddock                                       # e.g. ~/haddock
    cabal sandbox init
    cabal sandbox add-source haddock-library
    cabal sandbox add-source haddock-api
    cabal install haddock-library haddock-api
    cabal install -j4 --dependencies-only --enable-tests
    cabal configure --enable-tests
    cabal build -j4

or for now, you could just reupload the package with the `dist/doc/` I built. I can send it to you if you send me an e-mail at samboosalis@Gmail.com

(you don't really have to, but I've been using it to explore the code locally, and others might find it helpful too)

**Comment by ollef** [comment]
Done :)

**Comment by sboosali** [comment]
thanks!

(now for me to spend more time in https://hackage.haskell.org/package/Earley-0.10.0/docs/src/Text.Earley.Internal.html)
