### ISSUE TITLE
Generalize `word`?

### ISSUE THREAD

**Issue by sid-kap** [ollef/Earley#21]
Should `word` be generalized to 
```haskell
word :: (Eq t, ListLike i t) => i -> Prod r e t i
```
instead of
```haskell
word :: Eq t => [t] -> Prod r e t [t]
```
? 
This would make it easier to use values of type `Text` in particular.

**Comment by ollef** [comment]
That sounds convenient. If no one else has anything against it I say :+1: . Can you submit a pull request?

**Comment by sid-kap** [comment]
Sure! I'll try to send it later this week.

**Comment by phadej** [comment]
Might cause problems when used with `OvetloadedStrings`. I'd give new name to new more polymorphic

**Comment by ollef** [comment]
Done on master.
