### ISSUE TITLE
list = listLike?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ollef/Earley#32]
Wouldn't it be nicer to have `list = listLike`?

https://github.com/ollef/Earley/blob/master/Text/Earley/Derived.hs#L29

**Comment by ollef** [comment]
You're right, it probably would!

Can we think of any situations where this would lead to bad type inference?

**Comment by phadej** [comment]
@ollef no, it's about changing the definition of `list`, the type-signature would stay  the same (i.e. specific). IIRC we left `list` especially for the case where some `ListLike` was produced, to avoid annotating the intermediate type in `show . read` like situations.

**Comment by ollef** [comment]
Ah, then I misunderstood. Making this change without changing the type signature is uncontroversial. :)
