### ISSUE TITLE
A test suite is needed to prevent breaking changes

### ISSUE THREAD

**Issue by ollef** [ollef/Earley#4]

**Comment by phadej** [comment]
I can make a basic setup using http://hackage.haskell.org/package/tasty

**Comment by ollef** [comment]
That would be much appreciated. Tasty is what I had in mind as well.

**Comment by ollef** [comment]
Fixed by e459a2d6fd5957e511887fcddc696b66646414a6.

**Comment by phadej** [comment]
You're welcome! Now I convinced myself I can use this in production. Let's see if I can convince my teammates :)
