### ISSUE TITLE
INDENT and DEDENT

### ISSUE THREAD

**Issue by sorenbug** [ollef/Earley#49]
Is there a way to match INDENT/DEDENT or make parsers take an indentation level?

```
func foo(a: A, b: B): C =
  theresSomeIndentRequiredHere(a, b)

func noMoreIndentMeansNoMoreFoo: D = ???
```

**Comment by ollef** [comment]
Hey!

Good question.

There's no support built into the Earley library for indentation sensitivity, but perhaps a custom lexer could output such tokens for Earley to consume?

**Comment by sorenbug** [comment]
Any recommendations on how to do that effectively and efficiently?

**Comment by ollef** [comment]
I'm afraid I can't help you there, but perhaps someone else can?

**Comment by sorenbug** [comment]
[I've opened a StackOverflow question.](https://stackoverflow.com/questions/60922785/performant-way-to-lex-indent-and-dedent-to-pass-to-earley) If I get a reasonable answer, I'll post it here and close the issue.

**Comment by sorenbug** [comment]
I've been playing around with Megaparsec and Alex, both seem equally suited to handle this situation.
